// @ts-check
// Worker entry: HTTP router + cron handler.

import { authenticate } from './auth.js';
import * as db from './db.js';
import { addFeed, refreshFeed, runScheduled } from './fetcher.js';
import { SafeHtml } from './html.js';
import { articleImage } from './images.js';
import appleTouchIcon from './icons/apple-touch-icon.png';
import icon192 from './icons/icon-192.png';
import icon512Maskable from './icons/icon-512-maskable.png';
import icon512 from './icons/icon-512.png';
import { parseSubscription, sendToAll } from './push.js';
import { CSS, ICON_SVG, JS, MANIFEST, SW_JS, THEME_JS } from './static.js';
import * as views from './views.js';

const CSP = [
  "default-src 'none'",
  "script-src 'self'",
  "style-src 'self'",
  "img-src 'self'",
  "manifest-src 'self'",
  "worker-src 'self'",
  "connect-src 'self'",
  "form-action 'self'",
  "base-uri 'none'",
  "frame-ancestors 'none'",
  "require-trusted-types-for 'script'",
  'trusted-types sw-url', // the only policy: allows registering /sw.js (see /app.js)
].join('; ');

const SECURITY_HEADERS = {
  'content-security-policy': CSP,
  'x-content-type-options': 'nosniff',
  'referrer-policy': 'same-origin', // not 'no-referrer': that makes browsers send "Origin: null" on form posts
  'x-frame-options': 'DENY',
  'cross-origin-opener-policy': 'same-origin',
  'permissions-policy': 'camera=(), microphone=(), geolocation=()',
};

/** @param {BodyInit|null} body @param {number} status @param {Record<string,string>} headers */
function respond(body, status = 200, headers = {}) {
  return new Response(body, {
    status,
    headers: { 'cache-control': 'no-store', ...SECURITY_HEADERS, ...headers },
  });
}

/** @param {SafeHtml} page @param {number} [status] */
function htmlResponse(page, status = 200) {
  return respond(page.toString(), status, { 'content-type': 'text/html; charset=utf-8' });
}

/** @param {string} location */
function redirect(location) {
  return respond(null, 303, { location });
}

/** @param {number} status @param {string} message */
function errorResponse(status, message) {
  return htmlResponse(views.errorPage(status, message), status);
}

/**
 * Deployed version from the version_metadata binding, e.g. "a1b2c3d4 · 2026-09-25 14:03 UTC".
 * Cloudflare assigns a new id to every deployment; `wrangler dev` has none.
 * @param {any} env
 */
function versionLabel(env) {
  const v = env.CF_VERSION_METADATA;
  if (!v?.id) return 'dev';
  const when = v.timestamp ? ` · ${String(v.timestamp).slice(0, 16).replace('T', ' ')} UTC` : '';
  return `${String(v.id).slice(0, 8)}${when}`;
}

/**
 * Deploy id for asset URLs (/app.js?v=…). Every deploy gets new URLs, so a page can never run with a
 * cached script from the previous deploy (e.g. new HTML with a hidden button the old script never shows).
 * @param {any} env
 */
function assetVersion(env) {
  return String(env.CF_VERSION_METADATA?.id ?? 'dev').slice(0, 8);
}

/** Versioned asset URLs never change content, so they can be cached long; unversioned ones briefly. @param {URL} url */
function assetCache(url) {
  return url.searchParams.has('v') ? 'private, max-age=31536000, immutable' : 'private, max-age=300';
}

/** PNG app icons (generated by scripts/make-icons.mjs, bundled as binary data by wrangler). */
const ICONS = new Map([
  ['/apple-touch-icon.png', appleTouchIcon],
  ['/icon-192.png', icon192],
  ['/icon-512.png', icon512],
  ['/icon-512-maskable.png', icon512Maskable],
]);

/** Positive integer or null. @param {unknown} v */
function toId(v) {
  const n = Number(v);
  return Number.isSafeInteger(n) && n > 0 ? n : null;
}

/**
 * CSRF defence: state-changing requests must come from our own origin.
 * @param {Request} request @param {URL} url
 */
function isSameOrigin(request, url) {
  const origin = request.headers.get('origin');
  if (origin) return origin === url.origin;
  return request.headers.get('sec-fetch-site') === 'same-origin';
}

/** Where to go back to after a form post. @param {Request} request @param {URL} url */
function backTo(request, url, fallback = '/') {
  const ref = request.headers.get('referer');
  if (!ref) return fallback;
  try {
    const r = new URL(ref);
    // "//host/…" as a Location would be read as another host (protocol-relative URL).
    return r.origin === url.origin && !r.pathname.startsWith('//') ? r.pathname + r.search : fallback;
  } catch {
    return fallback;
  }
}

/** @param {any} env @param {URL} url */
async function renderTimeline(env, url) {
  const p = url.searchParams;
  const filterParam = p.get('filter');
  /** @type {import('./db.js').ArticleQuery} */
  const q = {
    topic: toId(p.get('topic')),
    feed: toId(p.get('feed')),
    filter: filterParam === 'all' || filterParam === 'starred' ? filterParam : 'unread',
    page: Math.min(toId(p.get('page')) ?? 0, 1000),
  };
  const [{ articles, hasMore }, nav] = await Promise.all([db.listArticles(env.DB, q), db.topicsWithCounts(env.DB)]);

  let heading = 'All articles';
  if (q.feed) heading = (await db.getFeed(env.DB, q.feed))?.title || 'Feed';
  else if (q.topic) heading = nav.topics.find((/** @type {any} */ t) => t.id === q.topic)?.name || 'Topic';

  return htmlResponse(
    views.layout({
      title: heading,
      active: 'home',
      topics: nav.topics,
      totalUnread: nav.totalUnread,
      version: versionLabel(env),
      assetVersion: assetVersion(env),
      currentTopic: q.topic,
      body: views.timeline({ articles, hasMore, q, heading }),
    })
  );
}

/**
 * @param {any} env
 * @param {{ error?: string, message?: string, formUrl?: string }} [extra]
 * @param {number} [status]
 */
async function renderFeeds(env, extra = {}, status = 200) {
  const [feeds, nav, subs] = await Promise.all([db.listFeeds(env.DB), db.topicsWithCounts(env.DB), db.listDevices(env.DB)]);
  const devices = subs.map((s) => ({ id: s.id, host: endpointHost(s.endpoint), createdAt: s.created_at, lastError: s.last_error }));
  return htmlResponse(
    views.layout({
      title: 'Feeds',
      active: 'feeds',
      topics: nav.topics,
      totalUnread: nav.totalUnread,
      version: versionLabel(env),
      assetVersion: assetVersion(env),
      body: views.feedsPage({ feeds, topics: nav.topics, pushKey: env.VAPID_PUBLIC_KEY ?? '', devices, ...extra }),
    }),
    status
  );
}

/** @param {any} env @param {string} [error] */
async function renderTopics(env, error) {
  const nav = await db.topicsWithCounts(env.DB);
  return htmlResponse(
    views.layout({
      title: 'Topics',
      active: 'topics',
      topics: nav.topics,
      totalUnread: nav.totalUnread,
      version: versionLabel(env),
      assetVersion: assetVersion(env),
      body: views.topicsPage({ topics: nav.topics, error }),
    }),
    error ? 400 : 200
  );
}

/** @param {unknown} v */
function cleanName(v) {
  return String(v ?? '').replace(/\s+/g, ' ').trim().slice(0, 50);
}

/** @param {Request} request @param {any} env @param {URL} url */
async function handlePost(request, env, url) {
  const path = url.pathname;
  const form = request.headers.get('content-type')?.includes('form') ? await request.formData() : new FormData();
  let m;

  // Articles
  if ((m = path.match(/^\/articles\/(\d+)\/([a-z]+)$/)) && db.isArticleAction(m[2])) {
    const state = await db.updateArticle(env.DB, Number(m[1]), m[2]);
    if (!state) return errorResponse(404, 'Article not found.');
    if (request.headers.get('x-requested-with') === 'fetch') {
      return respond(JSON.stringify(state), 200, { 'content-type': 'application/json' });
    }
    return redirect(backTo(request, url));
  }
  if (path === '/articles/mark-all-read') {
    await db.markAllRead(env.DB, { topic: toId(form.get('topic')), feed: toId(form.get('feed')), filter: 'unread', page: 0 });
    return redirect(backTo(request, url));
  }

  // Push notifications (JSON bodies, sent by /app.js)
  if (path.startsWith('/push/')) return handlePush(request, env, path);

  // Feeds
  if (path === '/feeds') {
    const inputUrl = String(form.get('url') ?? '');
    const result = await addFeed(env, inputUrl, toId(form.get('topic')));
    if (!result.ok) return renderFeeds(env, { error: result.error, formUrl: inputUrl }, 400);
    return renderFeeds(env, { message: `Added "${result.feed.title}" with ${result.added} articles.` });
  }
  if ((m = path.match(/^\/feeds\/(\d+)(?:\/(refresh|delete))?$/))) {
    const feed = await db.getFeed(env.DB, Number(m[1]));
    if (!feed) return errorResponse(404, 'Feed not found.');
    if (m[2] === 'delete') {
      await db.deleteFeed(env.DB, feed.id);
      return redirect('/feeds');
    }
    if (m[2] === 'refresh') {
      const r = await refreshFeed(env, feed);
      return renderFeeds(env, r.error ? { error: `Refresh failed: ${r.error}` } : { message: `${r.added} new articles.` });
    }
    await db.updateFeed(env.DB, feed.id, {
      topicId: toId(form.get('topic')),
      enabled: form.get('enabled') === '1',
      title: String(form.get('title') ?? '').trim().slice(0, 200) || feed.title,
    });
    return redirect('/feeds');
  }

  // Topics
  if (path === '/topics') {
    const name = cleanName(form.get('name'));
    if (!name) return renderTopics(env, 'Name is required.');
    try {
      await db.insertTopic(env.DB, name);
    } catch {
      return renderTopics(env, `Topic "${name}" already exists.`);
    }
    return redirect('/topics');
  }
  if ((m = path.match(/^\/topics\/(\d+)(\/delete)?$/))) {
    const id = Number(m[1]);
    if (m[2]) {
      await db.deleteTopic(env.DB, id);
      return redirect('/topics');
    }
    const name = cleanName(form.get('name'));
    if (!name) return renderTopics(env, 'Name is required.');
    try {
      await db.renameTopic(env.DB, id, name);
    } catch {
      return renderTopics(env, `Topic "${name}" already exists.`);
    }
    return redirect('/topics');
  }

  return errorResponse(404, 'Not found.');
}

/** @param {unknown} body */
function json(body, status = 200) {
  return respond(JSON.stringify(body), status, { 'content-type': 'application/json' });
}

/** @param {Request} request @param {any} env @param {string} path */
async function handlePush(request, env, path) {
  // Form post from the device list on /feeds.
  const remove = path.match(/^\/push\/devices\/(\d+)\/delete$/);
  if (remove) {
    await db.deleteSubscriptionById(env.DB, Number(remove[1]));
    console.warn(`push: device ${remove[1]} removed`);
    return redirect('/feeds');
  }

  const body = await request.json().catch(() => null);
  if (path === '/push/subscribe') {
    const sub = parseSubscription(body);
    if (!sub) {
      console.warn(`push: invalid subscription rejected (endpoint host: ${endpointHost(body?.endpoint)})`);
      return json({ ok: false, error: 'invalid subscription' }, 400);
    }
    await db.upsertSubscription(env.DB, sub);
    console.warn(`push: device subscribed (${endpointHost(sub.endpoint)})`);
    return json({ ok: true });
  }
  if (path === '/push/unsubscribe') {
    if (typeof body?.endpoint === 'string') {
      await db.deleteSubscription(env.DB, body.endpoint);
      console.warn(`push: device unsubscribed (${endpointHost(body.endpoint)})`);
    }
    return json({ ok: true });
  }
  if (path === '/push/test') {
    const r = await sendToAll(env, { title: 'RSS', body: 'Test notification – it works.', url: '/', tag: 'test' });
    console.log(`push: test sent ${r.sent}, failed ${r.failed}${r.error ? ` (${r.error})` : ''}`);
    return json(r);
  }
  return json({ ok: false, error: 'not found' }, 404);
}

/** Host of a push endpoint for logs and the device list — never the full URL (it acts as a token). @param {unknown} endpoint */
function endpointHost(endpoint) {
  try {
    return new URL(String(endpoint)).hostname.slice(0, 100);
  } catch {
    return 'invalid';
  }
}

/**
 * @param {Request} request @param {any} env @param {number} id
 * @param {{ waitUntil(p: Promise<unknown>): void }} ctx
 */
async function serveImage(request, env, ctx, id) {
  const img = await articleImage(request, env, ctx, id);
  // Missing or broken images are cached too, so the browser does not retry them on every page.
  if (!img) return respond(null, 404, { 'cache-control': 'private, max-age=86400' });
  return respond(img.body, 200, { 'content-type': img.type, 'cache-control': `private, max-age=${img.maxAge}` });
}

/**
 * @param {Request} request @param {any} env
 * @param {{ waitUntil(p: Promise<unknown>): void }} ctx
 */
async function handle(request, env, ctx) {
  const url = new URL(request.url);

  const auth = await authenticate(request, env);
  if (!auth.ok) {
    console.warn(`auth rejected: ${auth.reason}`);
    return respond('Unauthorized', 401, { 'content-type': 'text/plain; charset=utf-8' });
  }

  if (request.method === 'GET' || request.method === 'HEAD') {
    const img = url.pathname.match(/^\/img\/(\d+)$/);
    if (img) return serveImage(request, env, ctx, Number(img[1]));
    const icon = ICONS.get(url.pathname);
    if (icon) return respond(icon, 200, { 'content-type': 'image/png', 'cache-control': 'private, max-age=86400' });
    switch (url.pathname) {
      case '/':
        return renderTimeline(env, url);
      case '/feeds':
        return renderFeeds(env);
      case '/topics':
        return renderTopics(env);
      case '/app.css':
        return respond(CSS, 200, { 'content-type': 'text/css; charset=utf-8', 'cache-control': assetCache(url) });
      case '/app.js':
        return respond(JS, 200, { 'content-type': 'text/javascript; charset=utf-8', 'cache-control': assetCache(url) });
      case '/theme.js':
        return respond(THEME_JS, 200, { 'content-type': 'text/javascript; charset=utf-8', 'cache-control': assetCache(url) });
      case '/sw.js':
        // no-cache: the browser checks for a new service worker on every visit.
        return respond(SW_JS, 200, { 'content-type': 'text/javascript; charset=utf-8', 'cache-control': 'no-cache' });
      case '/manifest.webmanifest':
        return respond(MANIFEST, 200, { 'content-type': 'application/manifest+json', 'cache-control': 'private, max-age=3600' });
      case '/icon.svg':
        return respond(ICON_SVG, 200, { 'content-type': 'image/svg+xml', 'cache-control': 'private, max-age=86400' });
      case '/favicon.ico':
        return respond(null, 204);
      default:
        return errorResponse(404, 'Not found.');
    }
  }

  if (request.method === 'POST') {
    if (!isSameOrigin(request, url)) {
      console.warn(
        `csrf rejected: origin=${request.headers.get('origin')} sec-fetch-site=${request.headers.get('sec-fetch-site')} ` +
          `expected=${url.origin} host=${request.headers.get('host')}`
      );
      return errorResponse(403, 'Cross-origin request blocked.');
    }
    return handlePost(request, env, url);
  }

  return respond('Method not allowed', 405, { allow: 'GET, HEAD, POST' });
}

export default {
  /** @param {Request} request @param {any} env @param {{ waitUntil(p: Promise<unknown>): void }} ctx */
  async fetch(request, env, ctx) {
    try {
      return await handle(request, env, ctx);
    } catch (err) {
      console.error(err);
      return errorResponse(500, 'Something went wrong.');
    }
  },

  /** @param {any} _event @param {any} env @param {{ waitUntil(p: Promise<unknown>): void }} ctx */
  async scheduled(_event, env, ctx) {
    ctx.waitUntil(runScheduled(env));
  },
};
