// @ts-check
// Worker entry: HTTP router + cron handler.

import { authenticate } from './auth.js';
import { normalizeEmail, resolveUser } from './users.js';
import * as db from './db.js';
import { addFeed, refreshFeed, runScheduled } from './fetcher.js';
import { SafeHtml } from './html.js';
import { articleImage } from './images.js';
import { MAX_RULES_PER_USER, MUTE_SCAN_LIMIT, cleanPattern, isMuteField, matchRule, normalize, urlPattern } from './mute.js';
import appleTouchIcon from './icons/apple-touch-icon.png';
import icon192 from './icons/icon-192.png';
import icon512Maskable from './icons/icon-512-maskable.png';
import icon512 from './icons/icon-512.png';
import { parseSubscription, sendToUser } from './push.js';
import { CSS, ICON_SVG, JS, MANIFEST, SW_JS, THEME_JS } from './static.js';
import * as views from './views.js';

const CSP = [
  "default-src 'none'",
  "script-src 'self'",
  "style-src 'self'",
  "img-src 'self'",
  "manifest-src 'self'",
  "worker-src 'self'",
  "connect-src 'self'",
  "form-action 'self'",
  "base-uri 'none'",
  "frame-ancestors 'none'",
  "require-trusted-types-for 'script'",
  'trusted-types sw-url', // the only policy: allows registering /sw.js (see /app.js)
].join('; ');

const SECURITY_HEADERS = {
  'content-security-policy': CSP,
  'x-content-type-options': 'nosniff',
  'referrer-policy': 'same-origin', // not 'no-referrer': that makes browsers send "Origin: null" on form posts
  'x-frame-options': 'DENY',
  'cross-origin-opener-policy': 'same-origin',
  'permissions-policy': 'camera=(), microphone=(), geolocation=()',
};

/** @param {BodyInit|null} body @param {number} status @param {Record<string,string>} headers */
function respond(body, status = 200, headers = {}) {
  return new Response(body, {
    status,
    headers: { 'cache-control': 'no-store', ...SECURITY_HEADERS, ...headers },
  });
}

/** @param {SafeHtml} page @param {number} [status] */
function htmlResponse(page, status = 200) {
  return respond(page.toString(), status, { 'content-type': 'text/html; charset=utf-8' });
}

/** @param {string} location */
function redirect(location) {
  return respond(null, 303, { location });
}

/** @param {number} status @param {string} message */
function errorResponse(status, message) {
  return htmlResponse(views.errorPage(status, message), status);
}

/**
 * Deployed version from the version_metadata binding, e.g. "a1b2c3d4 · 2026-09-25 14:03 UTC".
 * Cloudflare assigns a new id to every deployment; `wrangler dev` has none.
 * @param {any} env
 */
function versionLabel(env) {
  const v = env.CF_VERSION_METADATA;
  if (!v?.id) return 'dev';
  const when = v.timestamp ? ` · ${String(v.timestamp).slice(0, 16).replace('T', ' ')} UTC` : '';
  return `${String(v.id).slice(0, 8)}${when}`;
}

/**
 * Deploy id for asset URLs (/app.js?v=…). Every deploy gets new URLs, so a page can never run with a
 * cached script from the previous deploy (e.g. new HTML with a hidden button the old script never shows).
 * @param {any} env
 */
function assetVersion(env) {
  return String(env.CF_VERSION_METADATA?.id ?? 'dev').slice(0, 8);
}

/** Versioned asset URLs never change content, so they can be cached long; unversioned ones briefly. @param {URL} url */
function assetCache(url) {
  return url.searchParams.has('v') ? 'private, max-age=31536000, immutable' : 'private, max-age=300';
}

/** PNG app icons (generated by scripts/make-icons.mjs, bundled as binary data by wrangler). */
const ICONS = new Map([
  ['/apple-touch-icon.png', appleTouchIcon],
  ['/icon-192.png', icon192],
  ['/icon-512.png', icon512],
  ['/icon-512-maskable.png', icon512Maskable],
]);

/** Domain part of an email for logs (the full address is never logged). @param {unknown} email */
function emailDomain(email) {
  const at = String(email ?? '').lastIndexOf('@');
  return at > 0 ? String(email).slice(at + 1, at + 101) : 'none';
}

/** Positive integer or null. @param {unknown} v */
function toId(v) {
  const n = Number(v);
  return Number.isSafeInteger(n) && n > 0 ? n : null;
}

/**
 * CSRF defence: state-changing requests must come from our own origin.
 * @param {Request} request @param {URL} url
 */
function isSameOrigin(request, url) {
  const origin = request.headers.get('origin');
  if (origin) return origin === url.origin;
  return request.headers.get('sec-fetch-site') === 'same-origin';
}

/** Where to go back to after a form post. @param {Request} request @param {URL} url */
function backTo(request, url, fallback = '/') {
  const ref = request.headers.get('referer');
  if (!ref) return fallback;
  try {
    const r = new URL(ref);
    // "//host/…" as a Location would be read as another host (protocol-relative URL).
    return r.origin === url.origin && !r.pathname.startsWith('//') ? r.pathname + r.search : fallback;
  } catch {
    return fallback;
  }
}

/** @typedef {{ id: number, email: string }} User the logged-in user (see handle()) */

/** @param {any} env @param {User} user @param {URL} url */
async function renderTimeline(env, user, url) {
  const p = url.searchParams;
  const filterParam = p.get('filter');
  /** @type {import('./db.js').ArticleQuery} */
  const q = {
    topic: toId(p.get('topic')),
    feed: toId(p.get('feed')),
    filter: filterParam === 'all' || filterParam === 'starred' ? filterParam : 'unread',
    page: Math.min(toId(p.get('page')) ?? 0, 1000),
  };
  const [{ articles, hasMore }, nav] = await Promise.all([db.listArticles(env.DB, user.id, q), db.topicsWithCounts(env.DB, user.id)]);

  let heading = 'All articles';
  if (q.feed) heading = (await db.getFeed(env.DB, user.id, q.feed))?.title || 'Feed';
  else if (q.topic) heading = nav.topics.find((/** @type {any} */ t) => t.id === q.topic)?.name || 'Topic';

  return htmlResponse(
    views.layout({
      title: heading,
      active: 'home',
      topics: nav.topics,
      totalUnread: nav.totalUnread,
      version: versionLabel(env),
      assetVersion: assetVersion(env),
      userEmail: user.email,
      currentTopic: q.topic,
      body: views.timeline({ articles, hasMore, q, heading }),
    })
  );
}

/**
 * @param {any} env
 * @param {User} user
 * @param {{ error?: string, message?: string, formUrl?: string }} [extra]
 * @param {number} [status]
 */
async function renderFeeds(env, user, extra = {}, status = 200) {
  const [feeds, nav, subs, muteRules] = await Promise.all([
    db.listFeeds(env.DB, user.id),
    db.topicsWithCounts(env.DB, user.id),
    db.listDevices(env.DB, user.id),
    db.listMuteRules(env.DB, user.id),
  ]);
  const devices = subs.map((s) => ({ id: s.id, host: endpointHost(s.endpoint), createdAt: s.created_at, lastError: s.last_error }));
  return htmlResponse(
    views.layout({
      title: 'Feeds',
      active: 'feeds',
      topics: nav.topics,
      totalUnread: nav.totalUnread,
      version: versionLabel(env),
      assetVersion: assetVersion(env),
      userEmail: user.email,
      body: views.feedsPage({ feeds, topics: nav.topics, pushKey: env.VAPID_PUBLIC_KEY ?? '', devices, muteRules, ...extra }),
    }),
    status
  );
}

/** @param {any} env @param {User} user @param {string} [error] */
async function renderTopics(env, user, error) {
  const nav = await db.topicsWithCounts(env.DB, user.id);
  return htmlResponse(
    views.layout({
      title: 'Topics',
      active: 'topics',
      topics: nav.topics,
      totalUnread: nav.totalUnread,
      version: versionLabel(env),
      assetVersion: assetVersion(env),
      userEmail: user.email,
      body: views.topicsPage({ topics: nav.topics, error }),
    }),
    error ? 400 : 200
  );
}

/**
 * The "Mute…" form for one article, pre-filled with its title (or URL path) and a preview of what the
 * rule would hide now.
 * @param {any} env @param {User} user @param {URL} url
 * @param {{ field?: string, pattern?: string, scope?: string, error?: string }} [form] values after a failed post
 */
async function renderMuteForm(env, user, url, form = {}) {
  const article = await db.getArticleForMute(env.DB, user.id, toId(url.searchParams.get('article')) ?? 0);
  if (!article) return errorResponse(404, 'Article not found.');
  const field = isMuteField(form.field ?? url.searchParams.get('field')) ? /** @type {'title'|'url'} */ (form.field ?? url.searchParams.get('field')) : 'title';
  const pattern = form.pattern ?? (field === 'url' ? urlPattern(article.url) : normalize(article.title));
  const [nav, candidates] = await Promise.all([db.topicsWithCounts(env.DB, user.id), db.muteCandidates(env.DB, user.id, null)]);
  const clean = cleanPattern(pattern);
  const rule = clean ? [{ id: 1, field, pattern: clean }] : [];
  const matches = candidates.filter((a) => matchRule(rule, a));
  return htmlResponse(
    views.layout({
      title: 'Mute',
      active: '',
      topics: nav.topics,
      totalUnread: nav.totalUnread,
      version: versionLabel(env),
      assetVersion: assetVersion(env),
      userEmail: user.email,
      body: views.muteForm({
        article,
        field,
        pattern,
        scope: form.scope === 'all' ? 'all' : 'feed',
        preview: { feed: matches.filter((a) => a.feed_id === article.feed_id).length, all: matches.length, limited: candidates.length >= MUTE_SCAN_LIMIT },
        error: form.error,
      }),
    }),
    form.error ? 400 : 200
  );
}

/**
 * Create a mute rule and hide what it matches now. Future articles are checked when they're fetched.
 * @param {any} env @param {User} user @param {URL} url @param {FormData} form
 */
async function createMuteRule(env, user, url, form) {
  const articleId = toId(form.get('article'));
  const article = articleId && (await db.getArticleForMute(env.DB, user.id, articleId));
  if (!article) return errorResponse(404, 'Article not found.');
  const field = form.get('field');
  const scope = form.get('scope') === 'all' ? 'all' : 'feed';
  const raw = String(form.get('pattern') ?? '');
  const back = new URL(`/mute/new?article=${article.id}`, url);
  const again = (/** @type {string} */ error) => renderMuteForm(env, user, back, { field: String(field), pattern: raw.slice(0, 300), scope, error });

  if (!isMuteField(field)) return again('Choose title or URL.');
  const pattern = cleanPattern(raw);
  if (!pattern) return again('The text must be 2–200 characters long.');
  if ((await db.countMuteRules(env.DB, user.id)) >= MAX_RULES_PER_USER) return again(`You already have ${MAX_RULES_PER_USER} mute rules. Delete one first.`);

  const feedId = scope === 'all' ? null : article.feed_id;
  // The rule is saved before existing articles are hidden. If that step is cut off (CPU limit), posting the
  // same rule again repeats it instead of failing with "already exists".
  const rule = (await db.insertMuteRule(env.DB, user.id, { feedId, field, pattern })) ?? (await db.findMuteRule(env.DB, user.id, { feedId, field, pattern }));
  if (!rule) return errorResponse(404, 'Feed not found.');
  const matches = (await db.muteCandidates(env.DB, user.id, feedId)).filter((a) => matchRule([rule], a));
  const hidden = await db.hideByMuteRule(env.DB, user.id, rule.id, matches.map((a) => a.id));
  return renderFeeds(env, user, { message: `Muted "${pattern}": ${hidden} ${hidden === 1 ? 'article' : 'articles'} hidden now, new ones stay hidden.` });
}

/** @param {unknown} v */
function cleanName(v) {
  return String(v ?? '').replace(/\s+/g, ' ').trim().slice(0, 50);
}

/**
 * Topic id from a form, only if it belongs to the user (else "no topic").
 * @param {any} env @param {User} user @param {unknown} value
 */
async function ownTopicId(env, user, value) {
  const id = toId(value);
  return id && (await db.ownsTopic(env.DB, user.id, id)) ? id : null;
}

/** @param {Request} request @param {any} env @param {User} user @param {URL} url */
async function handlePost(request, env, user, url) {
  const path = url.pathname;
  const form = request.headers.get('content-type')?.includes('form') ? await request.formData() : new FormData();
  let m;

  // Articles
  if ((m = path.match(/^\/articles\/(\d+)\/([a-z]+)$/)) && db.isArticleAction(m[2])) {
    const state = await db.updateArticle(env.DB, user.id, Number(m[1]), m[2]);
    if (!state) return errorResponse(404, 'Article not found.');
    if (request.headers.get('x-requested-with') === 'fetch') {
      return respond(JSON.stringify(state), 200, { 'content-type': 'application/json' });
    }
    return redirect(backTo(request, url));
  }
  if (path === '/articles/mark-all-read') {
    await db.markAllRead(env.DB, user.id, { topic: toId(form.get('topic')), feed: toId(form.get('feed')), filter: 'unread', page: 0 });
    return redirect(backTo(request, url));
  }

  // Mute rules
  if (path === '/mute') return createMuteRule(env, user, url, form);
  if ((m = path.match(/^\/mute\/(\d+)\/delete$/))) {
    if (!(await db.deleteMuteRule(env.DB, user.id, Number(m[1])))) return errorResponse(404, 'Rule not found.');
    return redirect('/feeds#muted');
  }

  // Push notifications (JSON bodies, sent by /app.js)
  if (path.startsWith('/push/')) return handlePush(request, env, user, path);

  // Feeds
  if (path === '/feeds') {
    const inputUrl = String(form.get('url') ?? '');
    const result = await addFeed(env, user.id, inputUrl, await ownTopicId(env, user, form.get('topic')));
    if (!result.ok) return renderFeeds(env, user, { error: result.error, formUrl: inputUrl }, 400);
    return renderFeeds(env, user, { message: `Added "${result.feed.title}" with ${result.added} articles.` });
  }
  if ((m = path.match(/^\/feeds\/(\d+)(?:\/(refresh|delete))?$/))) {
    const feed = await db.getFeed(env.DB, user.id, Number(m[1]));
    if (!feed) return errorResponse(404, 'Feed not found.');
    if (m[2] === 'delete') {
      await db.deleteFeed(env.DB, user.id, feed.id);
      return redirect('/feeds');
    }
    if (m[2] === 'refresh') {
      const r = await refreshFeed(env, feed);
      return renderFeeds(env, user, r.error ? { error: `Refresh failed: ${r.error}` } : { message: `${r.added} new articles.` });
    }
    await db.updateFeed(env.DB, user.id, feed.id, {
      topicId: await ownTopicId(env, user, form.get('topic')),
      enabled: form.get('enabled') === '1',
      title: String(form.get('title') ?? '').trim().slice(0, 200) || feed.title,
    });
    return redirect('/feeds');
  }

  // Topics
  if (path === '/topics') {
    const name = cleanName(form.get('name'));
    if (!name) return renderTopics(env, user, 'Name is required.');
    try {
      await db.insertTopic(env.DB, user.id, name);
    } catch {
      return renderTopics(env, user, `Topic "${name}" already exists.`);
    }
    return redirect('/topics');
  }
  if ((m = path.match(/^\/topics\/(\d+)(\/delete)?$/))) {
    const id = Number(m[1]);
    if (m[2]) {
      await db.deleteTopic(env.DB, user.id, id);
      return redirect('/topics');
    }
    const name = cleanName(form.get('name'));
    if (!name) return renderTopics(env, user, 'Name is required.');
    try {
      await db.renameTopic(env.DB, user.id, id, name);
    } catch {
      return renderTopics(env, user, `Topic "${name}" already exists.`);
    }
    return redirect('/topics');
  }

  return errorResponse(404, 'Not found.');
}

/** @param {unknown} body */
function json(body, status = 200) {
  return respond(JSON.stringify(body), status, { 'content-type': 'application/json' });
}

/** @param {Request} request @param {any} env @param {User} user @param {string} path */
async function handlePush(request, env, user, path) {
  // Form post from the device list on /feeds.
  const remove = path.match(/^\/push\/devices\/(\d+)\/delete$/);
  if (remove) {
    await db.deleteSubscriptionById(env.DB, user.id, Number(remove[1]));
    console.warn(`push: user ${user.id} removed device ${remove[1]}`);
    return redirect('/feeds');
  }

  const body = await request.json().catch(() => null);
  if (path === '/push/subscribe') {
    const sub = parseSubscription(body);
    if (!sub) {
      console.warn(`push: invalid subscription rejected (endpoint host: ${endpointHost(body?.endpoint)})`);
      return json({ ok: false, error: 'invalid subscription' }, 400);
    }
    await db.upsertSubscription(env.DB, user.id, sub);
    console.warn(`push: user ${user.id} subscribed a device (${endpointHost(sub.endpoint)})`);
    return json({ ok: true });
  }
  if (path === '/push/unsubscribe') {
    if (typeof body?.endpoint === 'string') {
      await db.deleteSubscription(env.DB, user.id, body.endpoint);
      console.warn(`push: user ${user.id} unsubscribed a device (${endpointHost(body.endpoint)})`);
    }
    return json({ ok: true });
  }
  if (path === '/push/test') {
    const r = await sendToUser(env, user.id, { title: 'RSS', body: 'Test notification – it works.', url: '/', tag: 'test' });
    console.log(`push: test for user ${user.id} sent ${r.sent}, failed ${r.failed}${r.error ? ` (${r.error})` : ''}`);
    return json(r);
  }
  return json({ ok: false, error: 'not found' }, 404);
}

/** Host of a push endpoint for logs and the device list — never the full URL (it acts as a token). @param {unknown} endpoint */
function endpointHost(endpoint) {
  try {
    return new URL(String(endpoint)).hostname.slice(0, 100);
  } catch {
    return 'invalid';
  }
}

/**
 * @param {Request} request @param {any} env @param {User} user @param {number} id
 * @param {{ waitUntil(p: Promise<unknown>): void }} ctx
 */
async function serveImage(request, env, user, ctx, id) {
  const img = await articleImage(request, env, ctx, user.id, id);
  // Missing or broken images are cached too, so the browser does not retry them on every page.
  if (!img) return respond(null, 404, { 'cache-control': 'private, max-age=86400' });
  return respond(img.body, 200, { 'content-type': img.type, 'cache-control': `private, max-age=${img.maxAge}` });
}

/**
 * @param {Request} request @param {any} env
 * @param {{ waitUntil(p: Promise<unknown>): void }} ctx
 */
async function handle(request, env, ctx) {
  const url = new URL(request.url);

  const auth = await authenticate(request, env);
  if (!auth.ok) {
    console.warn(`auth rejected: ${auth.reason}`);
    return respond('Unauthorized', 401, { 'content-type': 'text/plain; charset=utf-8' });
  }
  // Second gate after Access: the email must be on ALLOWED_EMAILS (src/users.js). Every handler below
  // only sees this user's data (src/db.js).
  const resolved = await resolveUser(env, auth.email);
  if ('error' in resolved) {
    // Only the domain is logged, never the full address.
    console.warn(`auth rejected: ${resolved.error} (email domain: ${emailDomain(auth.email)})`);
    return resolved.error === 'no-email'
      ? respond('Unauthorized', 401, { 'content-type': 'text/plain; charset=utf-8' })
      : respond('Forbidden: this account is not enabled for this reader.', 403, { 'content-type': 'text/plain; charset=utf-8' });
  }
  if (resolved.created) console.warn(`users: new user ${resolved.id} created on first login (email domain: ${emailDomain(auth.email)})`);
  /** @type {User} */
  const user = { id: resolved.id, email: normalizeEmail(auth.email) };

  if (request.method === 'GET' || request.method === 'HEAD') {
    const img = url.pathname.match(/^\/img\/(\d+)$/);
    if (img) return serveImage(request, env, user, ctx, Number(img[1]));
    const icon = ICONS.get(url.pathname);
    if (icon) return respond(icon, 200, { 'content-type': 'image/png', 'cache-control': 'private, max-age=86400' });
    switch (url.pathname) {
      case '/':
        return renderTimeline(env, user, url);
      case '/feeds':
        return renderFeeds(env, user);
      case '/topics':
        return renderTopics(env, user);
      case '/mute/new':
        return renderMuteForm(env, user, url);
      case '/app.css':
        return respond(CSS, 200, { 'content-type': 'text/css; charset=utf-8', 'cache-control': assetCache(url) });
      case '/app.js':
        return respond(JS, 200, { 'content-type': 'text/javascript; charset=utf-8', 'cache-control': assetCache(url) });
      case '/theme.js':
        return respond(THEME_JS, 200, { 'content-type': 'text/javascript; charset=utf-8', 'cache-control': assetCache(url) });
      case '/sw.js':
        // no-cache: the browser checks for a new service worker on every visit.
        return respond(SW_JS, 200, { 'content-type': 'text/javascript; charset=utf-8', 'cache-control': 'no-cache' });
      case '/manifest.webmanifest':
        return respond(MANIFEST, 200, { 'content-type': 'application/manifest+json', 'cache-control': 'private, max-age=3600' });
      case '/icon.svg':
        return respond(ICON_SVG, 200, { 'content-type': 'image/svg+xml', 'cache-control': 'private, max-age=86400' });
      case '/favicon.ico':
        return respond(null, 204);
      default:
        return errorResponse(404, 'Not found.');
    }
  }

  if (request.method === 'POST') {
    if (!isSameOrigin(request, url)) {
      console.warn(
        `csrf rejected: origin=${request.headers.get('origin')} sec-fetch-site=${request.headers.get('sec-fetch-site')} ` +
          `expected=${url.origin} host=${request.headers.get('host')}`
      );
      return errorResponse(403, 'Cross-origin request blocked.');
    }
    return handlePost(request, env, user, url);
  }

  return respond('Method not allowed', 405, { allow: 'GET, HEAD, POST' });
}

export default {
  /** @param {Request} request @param {any} env @param {{ waitUntil(p: Promise<unknown>): void }} ctx */
  async fetch(request, env, ctx) {
    try {
      return await handle(request, env, ctx);
    } catch (err) {
      console.error(err);
      return errorResponse(500, 'Something went wrong.');
    }
  },

  /** @param {any} _event @param {any} env @param {{ waitUntil(p: Promise<unknown>): void }} ctx */
  async scheduled(_event, env, ctx) {
    ctx.waitUntil(runScheduled(env));
  },
};
